backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"], description: "Enter Grade and Subject. Example: Math, First Grade" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: subjects
    label: Subjects
    folder: "subjects"
    slug: "{{slug}}"
    create: true
    fields:
      - { name: subject, label: Subject }
  - name: grades
    label: Grades
    folder: "grades"
    slug: "{{slug}}"
    create: true
    widget: number
    fields:
      - { name: grade, label: Grade }
  - name: "lesson"
    label: "Lesson"
    folder: lessons
    create: true    
    slug: "{{slug}}"
    fields:
      - name: title
        lable: Title
        widget: string
      - label: Grade
        name: grade
        widget: relation
        collection: grades
        search_fields: [grade]
        display_fields: [grade]
        value_field: grade
      - label: Subject
        name: subject
        widget: relation
        multiple: true
        description: Subject
        collection: subjects
        search_fields: [subject]
        display_fields: [subject]
        value_field: subject
      - label: Lesson Section
        name: section
        widget: list
        fields:
          - { label: "Image", name: image, widget: image, required: false }
          - { label: "Text", name: text, widget: markdown, required: false }
